store:
  mode: mysql
  load:
    mode: all
  mysql:
    jdbcUrl: jdbc:mysql://localhost:3306/ManageYourLog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username:
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
cache:
  mode: redis