server:
  port: 8000
receive:
  log:
    load:
      mode: http,mq
    kafka:
      bootstrap:
        servers: cartoon-ali.com:9092
      group:
        id: ManageYourLog
      topic: ManageYourLog
store:
  mode: default
  load:
    mode: default
  mysql:
    jdbcUrl: jdbc:mysql://cartoon-ali.com:3306/ManageYourLog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: test
    password: $Qwe13579
    driverClassName: com.mysql.cj.jdbc.Driver