server:
  port: 8000
store:
  method: default
  load:
    dao: mysql
  mysql:
    jdbcUrl: jdbc:mysql://cartoon-ali.com:3306/ManageYourLog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: test
    password: $Qwe13579
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml