spring:
  application:
    name: ManageYourLogDemo
upload:
  log:
    mode: rpc
    kafka:
      bootstrap:
        servers: cartoon-ali.com:9092
      topic: ManageYourLog
    rpc:
      ip: cartoon-ali.com
      port: 8848
      application:
        name: ManageYourLog
      protocol:
        name: dubbo
        port: 20882
        serialization: nativejava

