server:
  port: 8000
receive:
  log:
    load:
      mode: all
    kafka:
      bootstrap:
        servers: cartoon-ali.com:9092
      group:
        id: ManageYourLog
      topic: ManageYourLog
      rate: 10
    rpc:
      ip: cartoon-ali.com
      port: 8848
      application:
        name: ManageYourLog
      protocol:
        name: dubbo
        port: 20881
        serialization: hessian2
store:
  mode: mysql
  load:
    mode: mysql
  mysql:
    jdbcUrl: jdbc:mysql://cartoon-ali.com:3306/ManageYourLog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: test
    password: $Qwe13579
    driverClassName: com.mysql.cj.jdbc.Driver